// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: services/stockkeepingunit/proto/addstockcounthistorybycountry.proto

package addstockcounthistorybycountrypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StockKeepingUnit_AddStockCountHistoryforCountry_FullMethodName = "/stockkeepingunit.v1.StockKeepingUnit/AddStockCountHistoryforCountry"
)

// StockKeepingUnitClient is the client API for StockKeepingUnit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StockKeepingUnitClient interface {
	AddStockCountHistoryforCountry(ctx context.Context, in *StockCountAddRequestByCountry, opts ...grpc.CallOption) (*StockCountAddResponseByCountry, error)
}

type stockKeepingUnitClient struct {
	cc grpc.ClientConnInterface
}

func NewStockKeepingUnitClient(cc grpc.ClientConnInterface) StockKeepingUnitClient {
	return &stockKeepingUnitClient{cc}
}

func (c *stockKeepingUnitClient) AddStockCountHistoryforCountry(ctx context.Context, in *StockCountAddRequestByCountry, opts ...grpc.CallOption) (*StockCountAddResponseByCountry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockCountAddResponseByCountry)
	err := c.cc.Invoke(ctx, StockKeepingUnit_AddStockCountHistoryforCountry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StockKeepingUnitServer is the server API for StockKeepingUnit service.
// All implementations must embed UnimplementedStockKeepingUnitServer
// for forward compatibility.
type StockKeepingUnitServer interface {
	AddStockCountHistoryforCountry(context.Context, *StockCountAddRequestByCountry) (*StockCountAddResponseByCountry, error)
	mustEmbedUnimplementedStockKeepingUnitServer()
}

// UnimplementedStockKeepingUnitServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStockKeepingUnitServer struct{}

func (UnimplementedStockKeepingUnitServer) AddStockCountHistoryforCountry(context.Context, *StockCountAddRequestByCountry) (*StockCountAddResponseByCountry, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddStockCountHistoryforCountry not implemented")
}
func (UnimplementedStockKeepingUnitServer) mustEmbedUnimplementedStockKeepingUnitServer() {}
func (UnimplementedStockKeepingUnitServer) testEmbeddedByValue()                          {}

// UnsafeStockKeepingUnitServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StockKeepingUnitServer will
// result in compilation errors.
type UnsafeStockKeepingUnitServer interface {
	mustEmbedUnimplementedStockKeepingUnitServer()
}

func RegisterStockKeepingUnitServer(s grpc.ServiceRegistrar, srv StockKeepingUnitServer) {
	// If the following call pancis, it indicates UnimplementedStockKeepingUnitServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StockKeepingUnit_ServiceDesc, srv)
}

func _StockKeepingUnit_AddStockCountHistoryforCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockCountAddRequestByCountry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockKeepingUnitServer).AddStockCountHistoryforCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockKeepingUnit_AddStockCountHistoryforCountry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockKeepingUnitServer).AddStockCountHistoryforCountry(ctx, req.(*StockCountAddRequestByCountry))
	}
	return interceptor(ctx, in, info, handler)
}

// StockKeepingUnit_ServiceDesc is the grpc.ServiceDesc for StockKeepingUnit service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StockKeepingUnit_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stockkeepingunit.v1.StockKeepingUnit",
	HandlerType: (*StockKeepingUnitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddStockCountHistoryforCountry",
			Handler:    _StockKeepingUnit_AddStockCountHistoryforCountry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/stockkeepingunit/proto/addstockcounthistorybycountry.proto",
}
