// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: services/warehouse/proto/updatestockcountforwarehouselocation.proto

package updatestockcountforwarehouselocationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockCountUpdateRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	WarehouseLocationId int64                  `protobuf:"varint,1,opt,name=warehouseLocationId,proto3" json:"warehouseLocationId,omitempty"`
	WarehouseId         int64                  `protobuf:"varint,2,opt,name=warehouseId,proto3" json:"warehouseId,omitempty"`
	StockCount          map[string]int64       `protobuf:"bytes,3,rep,name=stockCount,proto3" json:"stockCount,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StockCountUpdateRequest) Reset() {
	*x = StockCountUpdateRequest{}
	mi := &file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockCountUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockCountUpdateRequest) ProtoMessage() {}

func (x *StockCountUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockCountUpdateRequest.ProtoReflect.Descriptor instead.
func (*StockCountUpdateRequest) Descriptor() ([]byte, []int) {
	return file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_rawDescGZIP(), []int{0}
}

func (x *StockCountUpdateRequest) GetWarehouseLocationId() int64 {
	if x != nil {
		return x.WarehouseLocationId
	}
	return 0
}

func (x *StockCountUpdateRequest) GetWarehouseId() int64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *StockCountUpdateRequest) GetStockCount() map[string]int64 {
	if x != nil {
		return x.StockCount
	}
	return nil
}

type StockCountUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       bool                   `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockCountUpdateResponse) Reset() {
	*x = StockCountUpdateResponse{}
	mi := &file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockCountUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockCountUpdateResponse) ProtoMessage() {}

func (x *StockCountUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockCountUpdateResponse.ProtoReflect.Descriptor instead.
func (*StockCountUpdateResponse) Descriptor() ([]byte, []int) {
	return file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_rawDescGZIP(), []int{1}
}

func (x *StockCountUpdateResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

var File_services_warehouse_proto_updatestockcountforwarehouselocation_proto protoreflect.FileDescriptor

const file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_rawDesc = "" +
	"\n" +
	"Cservices/warehouse/proto/updatestockcountforwarehouselocation.proto\x12\fwarehouse.v1\"\x83\x02\n" +
	"\x17StockCountUpdateRequest\x120\n" +
	"\x13warehouseLocationId\x18\x01 \x01(\x03R\x13warehouseLocationId\x12 \n" +
	"\vwarehouseId\x18\x02 \x01(\x03R\vwarehouseId\x12U\n" +
	"\n" +
	"stockCount\x18\x03 \x03(\v25.warehouse.v1.StockCountUpdateRequest.StockCountEntryR\n" +
	"stockCount\x1a=\n" +
	"\x0fStockCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"4\n" +
	"\x18StockCountUpdateResponse\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\bR\aupdated2\x82\x01\n" +
	"\tWarehouse\x12u\n" +
	"$UpdateStockcountForWarehouselocation\x12%.warehouse.v1.StockCountUpdateRequest\x1a&.warehouse.v1.StockCountUpdateResponseB_Z]warehouse/proto/updatestockcountforwarehouselocationpb;updatestockcountforwarehouselocationpbb\x06proto3"

var (
	file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_rawDescOnce sync.Once
	file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_rawDescData []byte
)

func file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_rawDescGZIP() []byte {
	file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_rawDescOnce.Do(func() {
		file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_rawDesc), len(file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_rawDesc)))
	})
	return file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_rawDescData
}

var file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_goTypes = []any{
	(*StockCountUpdateRequest)(nil),  // 0: warehouse.v1.StockCountUpdateRequest
	(*StockCountUpdateResponse)(nil), // 1: warehouse.v1.StockCountUpdateResponse
	nil,                              // 2: warehouse.v1.StockCountUpdateRequest.StockCountEntry
}
var file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_depIdxs = []int32{
	2, // 0: warehouse.v1.StockCountUpdateRequest.stockCount:type_name -> warehouse.v1.StockCountUpdateRequest.StockCountEntry
	0, // 1: warehouse.v1.Warehouse.UpdateStockcountForWarehouselocation:input_type -> warehouse.v1.StockCountUpdateRequest
	1, // 2: warehouse.v1.Warehouse.UpdateStockcountForWarehouselocation:output_type -> warehouse.v1.StockCountUpdateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_init() }
func file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_init() {
	if File_services_warehouse_proto_updatestockcountforwarehouselocation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_rawDesc), len(file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_goTypes,
		DependencyIndexes: file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_depIdxs,
		MessageInfos:      file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_msgTypes,
	}.Build()
	File_services_warehouse_proto_updatestockcountforwarehouselocation_proto = out.File
	file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_goTypes = nil
	file_services_warehouse_proto_updatestockcountforwarehouselocation_proto_depIdxs = nil
}
